name: Spellcheck

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run spellchecker
        run: npm run spellcheck
